FlashCard1/FlashCardApp/config/routes.rb
Rails.application.routes.draw do
  resources :cards
  devise_for :users
  resources :decks
  resources :cards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/', to: redirect('/users/sign_up')

  # Defines the root path route ("/")
  root "decks#index"
  get 'decks/:id/study', to: 'decks#study', as: 'study_deck'

end

FlashCard1/FlashCardApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

FlashCard1/FlashCardApp/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
end

FlashCard1/FlashCardApp/app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
end

FlashCard1/FlashCardApp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

FlashCard1/FlashCardApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def index

  end
end

FlashCard1/FlashCardApp/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    puts 'FOO'
    @card = Card.new(card_params)

    puts 'bar'

    respond_to do |format|
      if @card.save
        puts 'IF'
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        puts "ELSE"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:question, :answer, :deck_id)
    end
end

FlashCard1/FlashCardApp/app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: %i[ show edit update destroy ]

  # GET /decks or /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1 or /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks or /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to deck_url(@deck), notice: "Deck was successfully created." }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1 or /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to deck_url(@deck), notice: "Deck was successfully updated." }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1 or /decks/1.json
  def destroy
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url, notice: "Deck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deck_params
      params.require(:deck).permit(:name)
    end
  def study
    @cards = Card.where(deck_id: params[:id])
  end
end

FlashCard1/FlashCardApp/app/helpers/application_helper.rb
module ApplicationHelper
end

FlashCard1/FlashCardApp/app/helpers/cards_helper.rb
module CardsHelper
end

FlashCard1/FlashCardApp/app/helpers/decks_helper.rb
module DecksHelper
end

FlashCard1/FlashCardApp/app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p>
    <strong>Question:</strong>
    <%= card.question %>
  </p>

  <p>
    <strong>Answer:</strong>
    <%= card.answer %>
  </p>

  <p>
    <strong>Deck:</strong>
    <%= card.deck_id %>
  </p>

</div>

FlashCard1/FlashCardApp/app/views/cards/_form.html.erb
<%= form_with(model: card) do |form| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question, style: "display: block" %>
    <%= form.text_field :question %>
  </div>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.text_field :answer %>
  </div>

  <div>
    <%= form.label :deck_id, style: "display: block" %>
    <%= form.text_field :deck_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

FlashCard1/FlashCardApp/app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

FlashCard1/FlashCardApp/app/views/cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cards</h1>

<div id="cards">
  <% @cards.each do |card| %>
    <%= render card %>
    <p>
      <%= link_to "Show this card", card %>
    </p>
  <% end %>
</div>

<%= link_to "New card", new_card_path %>

FlashCard1/FlashCardApp/app/views/cards/new.html.erb
<h1>New card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Back to cards", cards_path %>
</div>

FlashCard1/FlashCardApp/app/views/cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @card %>

<div>
  <%= link_to "Edit this card", edit_card_path(@card) %> |
  <%= link_to "Back to cards", cards_path %>

  <%= button_to "Destroy this card", @card, method: :delete %>
</div>

FlashCard1/FlashCardApp/app/views/decks/_deck.html.erb
<div id="<%= dom_id deck %>">
  <p>
    <strong>Name:</strong>
    <%= deck.name %>
  </p>

</div>

FlashCard1/FlashCardApp/app/views/decks/_form.html.erb
<%= form_with(model: deck) do |form| %>
  <% if deck.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
        <% deck.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

FlashCard1/FlashCardApp/app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render "form", deck: @deck %>

<br>

<div>
  <%= link_to "Show this deck", @deck %> |
  <%= link_to "Back to decks", decks_path %>
</div>

FlashCard1/FlashCardApp/app/views/decks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Decks</h1>

<div id="decks">
  <% @decks.each do |deck| %>
    <%= render deck %>
    <p>
      <%= link_to "Show this deck", deck %>
    </p>
  <% end %>
</div>

<%= link_to "New deck", new_deck_path %>

FlashCard1/FlashCardApp/app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render "form", deck: @deck %>

<br>

<div>
  <%= link_to "Back to decks", decks_path %>
</div>

FlashCard1/FlashCardApp/app/views/decks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @deck %>
<%= render Card.where(deck_id: params[:id]) %>


<div>
  <%= link_to "Edit this deck", edit_deck_path(@deck) %> |
  <%= link_to "Back to decks", decks_path %>

  <%= button_to "Destroy this deck", @deck, method: :delete %>
</div>

FlashCard1/FlashCardApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashCardApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>

  <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link", data: {"turbo-method": "delete"} %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
  </p>

  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="/ideas">Ideas</a>
    </li>
    ...
  </ul>




  </body>
</html>